<a href="https://colab.research.google.com/github/10933140/10933140/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

格點

In [1]:
import numpy as np

In [12]:
x = np.array([1, 2, 3])

In [5]:
x

array([1, 2, 3])

基本運算

In [6]:
a = np.array([1, 2, 3, 6])
b = np.linspace(0, 2, 4)
c = a - b

In [7]:
c

array([1.        , 1.33333333, 1.66666667, 4.        ])

全域方法

In [8]:
a = np.linspace(-np.pi, np.pi, 100)

In [9]:
b = np.sin(a)

線性代數

In [11]:
from numpy.random import rand
from numpy.linalg import solve, inv
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])